export type Employee = {
  id: string;
  name: string;
  email: string;
  photo: string;
  department: string;
  designation: string;
  location: 'Head Office' | 'Zonal Office' | 'Labour Colony';
  zone: string;
  employmentType: 'Permanent' | 'Contract' | 'Daily-wage';
  joiningDate: string;
  status: 'Active' | 'Inactive';
};

export const employees: Employee[] = [
  {
    id: 'EMP001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Technology',
    designation: 'Software Engineer',
    location: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    joiningDate: '2022-08-15',
    status: 'Active',
  },
  {
    id: 'EMP002',
    name: 'Diya Patel',
    email: 'diya.patel@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Human Resources',
    designation: 'HR Manager',
    location: 'Zonal Office',
    zone: 'North Zone',
    employmentType: 'Permanent',
    joiningDate: '2021-05-20',
    status: 'Active',
  },
  {
    id: 'EMP003',
    name: 'Rohan Kumar',
    email: 'rohan.kumar@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Labourer',
    location: 'Labour Colony',
    zone: 'Colony 5',
    employmentType: 'Daily-wage',
    joiningDate: '2023-01-10',
    status: 'Active',
  },
  {
    id: 'EMP004',
    name: 'Priya Singh',
    email: 'priya.singh@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Finance',
    designation: 'Accountant',
    location: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    joiningDate: '2020-11-30',
    status: 'Active',
  },
  {
    id: 'EMP005',
    name: 'Amit Kumar',
    email: 'amit.kumar@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Marketing',
    designation: 'Marketing Executive',
    location: 'Zonal Office',
    zone: 'East Zone',
    employmentType: 'Contract',
    joiningDate: '2023-03-01',
    status: 'Active',
  },
  {
    id: 'EMP006',
    name: 'Sunita Devi',
    email: 'sunita.devi@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Supervisor',
    location: 'Labour Colony',
    zone: 'Colony 2',
    employmentType: 'Permanent',
    joiningDate: '2019-07-22',
    status: 'Active',
  },
  {
    id: 'EMP007',
    name: 'Vikram Rathod',
    email: 'vikram.rathod@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Technology',
    designation: 'System Analyst',
    location: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    joiningDate: '2022-09-01',
    status: 'Inactive',
  },
  {
    id: 'EMP008',
    name: 'Anjali Verma',
    email: 'anjali.verma@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Human Resources',
    designation: 'HR Assistant',
    location: 'Zonal Office',
    zone: 'West Zone',
    employmentType: 'Contract',
    joiningDate: '2023-06-12',
    status: 'Active',
  },
  {
    id: 'EMP009',
    name: 'Manoj Yadav',
    email: 'manoj.yadav@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Labourer',
    location: 'Labour Colony',
    zone: 'Colony 5',
    employmentType: 'Daily-wage',
    joiningDate: '2023-02-18',
    status: 'Active',
  },
  {
    id: 'EMP010',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Finance',
    designation: 'Senior Accountant',
    location: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    joiningDate: '2018-04-16',
    status: 'Active',
  },
    {
    id: 'EMP011',
    name: 'Kavita Gupta',
    email: 'kavita.gupta@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Technology',
    designation: 'UI/UX Designer',
    location: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    joiningDate: '2022-11-10',
    status: 'Active',
  },
  {
    id: 'EMP012',
    name: 'Rajesh Mehra',
    email: 'rajesh.mehra@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Zonal Manager',
    location: 'Zonal Office',
    zone: 'South Zone',
    employmentType: 'Permanent',
    joiningDate: '2017-09-05',
    status: 'Active',
  },
  {
    id: 'EMP013',
    name: 'Suresh Ram',
    email: 'suresh.ram@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Labourer',
    location: 'Labour Colony',
    zone: 'Colony 1',
    employmentType: 'Daily-wage',
    joiningDate: '2023-04-02',
    status: 'Inactive',
  },
  {
    id: 'EMP014',
    name: 'Neha Desai',
    email: 'neha.desai@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Marketing',
    designation: 'Digital Marketer',
    location: 'Zonal Office',
    zone: 'West Zone',
    employmentType: 'Contract',
    joiningDate: '2022-08-20',
    status: 'Active',
  },
  {
    id: 'EMP015',
    name: 'Arjun Singh',
    email: 'arjun.singh@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Technology',
    designation: 'DevOps Engineer',
    location: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    joiningDate: '2021-12-01',
    status: 'Active',
  },
];
