export type Transfer = {
  station: string;
  fromDate: string;
  toDate: string | null;
};

export type Employee = {
  id: string;
  fullName: string;
  fatherName: string;
  cnic: string;
  mobileNumber: string;
  email: string;
  photo: string;
  department: string;
  designation: string;
  station: 'Head Office' | 'Zonal Office' | 'Labour Colony';
  zone: string;
  employmentType: 'Permanent' | 'Contract' | 'Daily-wage';
  dateOfAppointment: string;
  dateOfBirth: string;
  stationOfAppointment: string;
  transferHistory: Transfer[];
  status: 'Active' | 'Inactive';
};

export const employees: Employee[] = [
  {
    id: 'EMP001',
    fullName: 'Aarav Sharma',
    fatherName: 'Suresh Sharma',
    cnic: '12345-1234567-1',
    mobileNumber: '0300-1234567',
    email: 'aarav.sharma@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Technology',
    designation: 'Software Engineer',
    station: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    dateOfAppointment: '2022-08-15',
    dateOfBirth: '1995-02-20',
    stationOfAppointment: 'Head Office',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP002',
    fullName: 'Diya Patel',
    fatherName: 'Ramesh Patel',
    cnic: '12345-1234567-2',
    mobileNumber: '0300-2345678',
    email: 'diya.patel@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Human Resources',
    designation: 'HR Manager',
    station: 'Zonal Office',
    zone: 'North Zone',
    employmentType: 'Permanent',
    dateOfAppointment: '2021-05-20',
    dateOfBirth: '1990-08-10',
    stationOfAppointment: 'North Zone Office',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP003',
    fullName: 'Rohan Kumar',
    fatherName: 'Anil Kumar',
    cnic: '12345-1234567-3',
    mobileNumber: '0300-3456789',
    email: 'rohan.kumar@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Labourer',
    station: 'Labour Colony',
    zone: 'Colony 5',
    employmentType: 'Daily-wage',
    dateOfAppointment: '2023-01-10',
    dateOfBirth: '1998-12-05',
    stationOfAppointment: 'Colony 5',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP004',
    fullName: 'Priya Singh',
    fatherName: 'Vikram Singh',
    cnic: '12345-1234567-4',
    mobileNumber: '0300-4567890',
    email: 'priya.singh@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Finance',
    designation: 'Accountant',
    station: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    dateOfAppointment: '2020-11-30',
    dateOfBirth: '1992-06-25',
    stationOfAppointment: 'Head Office',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP005',
    fullName: 'Amit Kumar',
    fatherName: 'Sunil Kumar',
    cnic: '12345-1234567-5',
    mobileNumber: '0300-5678901',
    email: 'amit.kumar@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Marketing',
    designation: 'Marketing Executive',
    station: 'Zonal Office',
    zone: 'East Zone',
    employmentType: 'Contract',
    dateOfAppointment: '2023-03-01',
    dateOfBirth: '1996-04-12',
    stationOfAppointment: 'East Zone Office',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP006',
    fullName: 'Sunita Devi',
    fatherName: 'Rajesh Devi',
    cnic: '12345-1234567-6',
    mobileNumber: '0300-6789012',
    email: 'sunita.devi@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Supervisor',
    station: 'Labour Colony',
    zone: 'Colony 2',
    employmentType: 'Permanent',
    dateOfAppointment: '2019-07-22',
    dateOfBirth: '1988-11-30',
    stationOfAppointment: 'Colony 2',
    transferHistory: [
      { station: 'Colony 5', fromDate: '2021-01-01', toDate: '2022-12-31' },
    ],
    status: 'Active',
  },
  {
    id: 'EMP007',
    fullName: 'Vikram Rathod',
    fatherName: 'Sanjay Rathod',
    cnic: '12345-1234567-7',
    mobileNumber: '0300-7890123',
    email: 'vikram.rathod@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Technology',
    designation: 'System Analyst',
    station: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    dateOfAppointment: '2022-09-01',
    dateOfBirth: '1993-01-15',
    stationOfAppointment: 'Head Office',
    transferHistory: [],
    status: 'Inactive',
  },
  {
    id: 'EMP008',
    fullName: 'Anjali Verma',
    fatherName: 'Ravi Verma',
    cnic: '12345-1234567-8',
    mobileNumber: '0300-8901234',
    email: 'anjali.verma@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Human Resources',
    designation: 'HR Assistant',
    station: 'Zonal Office',
    zone: 'West Zone',
    employmentType: 'Contract',
    dateOfAppointment: '2023-06-12',
    dateOfBirth: '1997-07-07',
    stationOfAppointment: 'West Zone Office',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP009',
    fullName: 'Manoj Yadav',
    fatherName: 'Dinesh Yadav',
    cnic: '12345-1234567-9',
    mobileNumber: '0300-9012345',
    email: 'manoj.yadav@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Labourer',
    station: 'Labour Colony',
    zone: 'Colony 5',
    employmentType: 'Daily-wage',
    dateOfAppointment: '2023-02-18',
    dateOfBirth: '2000-03-22',
    stationOfAppointment: 'Colony 5',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP010',
    fullName: 'Sneha Reddy',
    fatherName: 'Arjun Reddy',
    cnic: '23456-2345678-0',
    mobileNumber: '0301-1234567',
    email: 'sneha.reddy@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Finance',
    designation: 'Senior Accountant',
    station: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    dateOfAppointment: '2018-04-16',
    dateOfBirth: '1991-09-18',
    stationOfAppointment: 'Head Office',
    transferHistory: [],
    status: 'Active',
  },
    {
    id: 'EMP011',
    fullName: 'Kavita Gupta',
    fatherName: 'Ashok Gupta',
    cnic: '23456-2345678-1',
    mobileNumber: '0301-2345678',
    email: 'kavita.gupta@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Technology',
    designation: 'UI/UX Designer',
    station: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    dateOfAppointment: '2022-11-10',
    dateOfBirth: '1994-10-28',
    stationOfAppointment: 'Head Office',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP012',
    fullName: 'Rajesh Mehra',
    fatherName: 'Vijay Mehra',
    cnic: '23456-2345678-2',
    mobileNumber: '0301-3456789',
    email: 'rajesh.mehra@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Zonal Manager',
    station: 'Zonal Office',
    zone: 'South Zone',
    employmentType: 'Permanent',
    dateOfAppointment: '2017-09-05',
    dateOfBirth: '1985-05-14',
    stationOfAppointment: 'South Zone Office',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP013',
    fullName: 'Suresh Ram',
    fatherName: 'Gopal Ram',
    cnic: '23456-2345678-3',
    mobileNumber: '0301-4567890',
    email: 'suresh.ram@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Operations',
    designation: 'Labourer',
    station: 'Labour Colony',
    zone: 'Colony 1',
    employmentType: 'Daily-wage',
    dateOfAppointment: '2023-04-02',
    dateOfBirth: '1999-01-01',
    stationOfAppointment: 'Colony 1',
    transferHistory: [],
    status: 'Inactive',
  },
  {
    id: 'EMP014',
    fullName: 'Neha Desai',
    fatherName: 'Mahesh Desai',
    cnic: '23456-2345678-4',
    mobileNumber: '0301-5678901',
    email: 'neha.desai@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Marketing',
    designation: 'Digital Marketer',
    station: 'Zonal Office',
    zone: 'West Zone',
    employmentType: 'Contract',
    dateOfAppointment: '2022-08-20',
    dateOfBirth: '1996-08-20',
    stationOfAppointment: 'West Zone Office',
    transferHistory: [],
    status: 'Active',
  },
  {
    id: 'EMP015',
    fullName: 'Arjun Singh',
    fatherName: 'Ranbir Singh',
    cnic: '23456-2345678-5',
    mobileNumber: '0301-6789012',
    email: 'arjun.singh@example.com',
    photo: 'https://placehold.co/100x100.png',
    department: 'Technology',
    designation: 'DevOps Engineer',
    station: 'Head Office',
    zone: 'HO-1',
    employmentType: 'Permanent',
    dateOfAppointment: '2021-12-01',
    dateOfBirth: '1992-03-03',
    stationOfAppointment: 'Head Office',
    transferHistory: [],
    status: 'Active',
  },
];